#Using the base image with Python 3.10
# FROM python:3.10
FROM python:3.10

#Set our working directory as app
WORKDIR /app

COPY RequiredFilesForDocker ./app

#Installing Python packages through requirements.txt file
RUN pip install --no-cache-dir -r requirements.txt


#Exposing port 8501 from the container
EXPOSE 8501
#Starting the Python application
#CMD ["gunicorn", "--bind", "0.0.0.0:5000", "script:app"]
ENTRYPOINT ["streamlit", "run", "script.py", "--server.port=8501", "--server.address=0.0.0.0"]